url: https://nizatto.com/

# Site settings
title: Nizatto Digital Solutions
email: hello@nizatto.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Will
  pic: 1
  position: Creative Director
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #
- name: Ryan
  pic: 2
  position: Operations Director
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #
- name: Lauren
  pic: 3
  position: Project Champion
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #
- name: David
  pic: 4
  position: Web Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/nizatto/
  - title: facebook
    url: https://www.facebook.com/nizatto/
  - title: instagram
    url: https://www.instagram.com/nizattodigital/
  - title: linkedin
    url: https://www.linkedin.com/company/nizatto/

# Postal address (add as many lines as necessary)
address:
  - line: 120 Clarence Road
  - line: Horsham RH10 1AB

# Build settings
markdown: kramdown
permalink: pretty
